# are alma9 and centos7 the only options?
image: artifacts.ncei.noaa.gov/ncei/base:alma9
variables:
  NODE_VERSION: "v18.15.0"

stages:          # List of stages for jobs, and their order of execution
  - .pre
  # - test
  - build
  # - deploy


setup-job:
  stage: .pre
  cache:
  - key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  - key: $NODE_VERSION
    paths:
      - node-$NODE_VERSION-linux-x64/
    policy: push
  script:
    # WARNING: not the latest version of LTS/Hydrogen
    - curl -o node-$NODE_VERSION-linux-x64.tar.gz https://artifacts.ncei.noaa.gov:443/artifactory/node-dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz
    # not permitted?
    # - curl -o node-$NODE_VERSION-linux-x64.tar.gz https://node.js.org/download/release/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz
    - tar -xzf node-$NODE_VERSION-linux-x64.tar.gz 
    - export PATH=$PATH:$PWD/node-$NODE_VERSION-linux-x64/bin
    # set up npm registry and CA certs
    - npm config set registry https://artifacts.ncei.noaa.gov/artifactory/api/npm/npm.upstream/
    - export NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt
    - npm -d install
  

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  cache:
  - key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  - key: $NODE_VERSION
    paths:
      - node-$NODE_VERSION-linux-x64/
    policy: pull
  script:
    # TODO why is the node install not pulled from cache?
    # WARNING: not the latest version of LTS/Hydrogen
    - curl -o node-$NODE_VERSION-linux-x64.tar.gz https://artifacts.ncei.noaa.gov:443/artifactory/node-dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz
    - tar -xzf node-$NODE_VERSION-linux-x64.tar.gz 
    - export PATH=$PATH:$PWD/node-$NODE_VERSION-linux-x64/bin
    - npm config set registry https://artifacts.ncei.noaa.gov/artifactory/api/npm/npm.upstream/
    - export NODE_EXTRA_CA_CERTS=/etc/pki/tls/certs/ca-bundle.crt
    - export PATH=$PATH:$PWD/node-$NODE_VERSION-linux-x64/bin
    - echo "installed node/npm version `node --version`/`npm --version`"    
    #- echo "Linting code..."
    #- npm run lint
    #- echo "Running unit tests..."
    #- npm run test
    #- echo "Running code coverage..."
    #- npm run coverage
    - echo "Running build..."
    #- npm run build
    - npx vite build -m test --base /maps/imlgs/
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH    

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."

# TODO security scanner not available in NCEI archive  
# sast:
#   stage: test
# include:
#   - template: Security/SAST.gitlab-ci.yml


